<?php

namespace App\Console\Commands;

use Illuminate\Console\GeneratorCommand;

class MakeServiceCommand extends GeneratorCommand
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'make:service {name}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = '创建 service';


    protected function getDefaultNamespace($rootNamespace)
    {
        return $rootNamespace . '\Http\Services'; // TODO: Change the autogenerated stub
    }

    protected function getStub()
    {
        // TODO: Implement getStub() method.
        return __DIR__ . '/Stubs/services.stub';
    }
}
